name: Crops

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Pyrbu.yml'
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  ZNPCsPlus:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Xiao-MoMi/Custom-Crops"
      name: "CustomCrops"
      java: "17"
      target: "plugin/build/libs/*.jar"
