name: Crops

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Crops.yml'
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  CustomCrops:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Xiao-MoMi/Custom-Crops"
      name: "CustomCrops"
      java: "21"
      target: "target/CustomCrops-*.jar"
