name: GaLaXyILY

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/GaLaXyILY.yml'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  NoDamageParticle:
    uses: GaLaXyILY/PLUGIN/.github/workflows/maven-build.yml@main
    with:
      repository: "GaLaXyILY/HotkeyEvent"
      name: "NoDamageParticle"
      java: 21
