name: Maxlego08

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Maxlego08.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  zEssentials:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Maxlego08/zEssentials"
      name: "zEssentials"
      java: 17
      target: "target/*"
