name: PQguanfang

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/PQguanfang.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  MythicTotem:
    uses: GaLaXyILY/PLUGIN/.github/workflows/maven-build.yml@main
    with:
      repository: "PQguanfang/MythicTotem"
      name: "MythicTotem"
      java: 21
      tasks: "clean package -DskipTests"
