name: TerraTrees

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/TerraTrees.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  zEssentials:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "RabbitTV22/TerraTrees"
      name: "TerraTrees"
      java: 21
