name: TerraTrees

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/TerraTrees.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  RayTraceAntiXray:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "TauCubed/RayTraceAntiXray"
      name: "RayTraceAntiXray"
      java: 21
  TerraTrees:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "RabbitTV22/TerraTrees"
      name: "TerraTrees"
      java: 21
  HMCCosmetics:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "HibiscusMC/HMCCosmetics"
      name: "HMCCosmetics"
      java: 21
  HibiscusCommons:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "HibiscusMC/HibiscusCommons"
      name: "HibiscusCommons"
      java: 21
