name: tooltips

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tooltips.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  tooltips:
    uses: GaLaXyILY/PLUGIN/.github/workflows/maven-build.yml@main
    with:
      repository: "Septicuss/tooltips"
      name: "tooltips"
      java: 21
      tasks: "clean package -DskipTests"
