name: toxicity188

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/toxicity188.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  BetterHealthBar3:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "toxicity188/BetterHealthBar3"
      name: "BetterHealthBar3"
      java: 17
      
  BetterModel:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "toxicity188/BetterModel"
      name: "BetterModel"
      java: 17
      
  BetterDamage:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "toxicity188/BetterDamage"
      name: "BetterDamage"
      java: 21

