name: Xiao-MoMi

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Xiao-MoMi.yml'
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  CustomCrops:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Xiao-MoMi/Custom-Crops"
      name: "CustomCrops"
      java: "21"
      target: "target/CustomCrops-*.jar"
      
  CustomFishing:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Xiao-MoMi/Custom-Fishing"
      name: "CustomFishing"
      java: "21"
      target: "target/CustomFishing-*.jar"

  Custom-Nameplates:
    uses: GaLaXyILY/PLUGIN/.github/workflows/gradle-build.yml@main
    with:
      repository: "Xiao-MoMi/Custom-Nameplates"
      name: "Custom-Nameplates"
      java: "21"
      target: "target/Custom-Nameplates-*.jar"
